#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/border_collie
#
# IDENTIFICATION
#    src/backend/access/border_collie/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/border_collie
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	border_collie.o

include $(top_srcdir)/src/backend/common.mk
